apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - "namespace.yaml"
helmCharts:
  - name: cloudnative-pg
    namespace: cnpg-system
    releaseName: cnpg
    version: 0.22.1
    repo: https://cloudnative-pg.github.io/charts
    includeCRDs: true
