apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      initContainers:
        - name: create-user
          image: eclipse-mosquitto:latest
          command:
            - mosquitto_passwd
            - -b
            - -c
            - /mosquitto/passwd
            - $(MOSQUITTO_USERNAME)
            - $(MOSQUITTO_PASSWORD)
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 64Mi
          envFrom:
            - secretRef:
                name: mosquitto
          volumeMounts:
            - mountPath: /mosquitto
              name: passwd
      containers:
        - envFrom:
            - secretRef:
                name: mosquitto
          image: eclipse-mosquitto:latest
          name: mosquitto
          ports:
            - containerPort: 1883
              name: mqtt
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 100Mi
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: config
              subPath: mosquitto.conf
            - mountPath: /mosquitto/passwd
              name: passwd
              subPath: passwd
      securityContext:
        runAsGroup: 1883
        runAsUser: 1883
        fsGroup: 1000
      volumes:
        - configMap:
            name: mosquitto
          name: config
        - emptyDir: {}
          name: passwd
