apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: mosquitto-0.0.1
  name: mosquitto
  namespace: mosquitto
spec:
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: mosquitto-0.0.1
  name: mosquitto-lb
  namespace: mosquitto
spec:
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  type: LoadBalancer
