apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"
  url: https://argocd.sjoedin.se
  dex.config: |
    connectors:
    - config:
        issuer: https://authentik.sjoedin.se/application/o/argocd/
        clientID: $dex.authentik.clientID
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik
