apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
