apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt
stringData:
  MQTT_USERNAME: "{{ .MOSQUITTO_USERNAME }}"
  MQTT_PASSWORD: "{{ .MOSQUITTO_PASSWORD }}"
  USB_DEVICES_URL: "{{ .USB_DEVICES_URL }}"
