resources:
  - "../../base/zigbee2mqtt"
namespace: zigbee2mqtt

images:
  - name: koenkk/zigbee2mqtt
    newTag: 1.39.0

secretGenerator:
  - name: zigbee2mqtt
    envs: [".env"]
    options:
      disableNameSuffixHash: true
transformers:
  - "ESTransformer.yaml"
