apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - secret.yaml
  - scheduled-backup.yaml
components:
  - ../external-secrets-transformer
patches:
  - path: cluster-patch.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster

replacements:
  - source:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      fieldPath: metadata.name
    targets:
      - select:
          group: postgresql.cnpg.io
          version: v1
          kind: ScheduledBackup
          name: scheduledBackupName
        fieldPaths:
          - metadata.name
          - spec.cluster.name
      - select:
          group: postgresql.cnpg.io
          version: v1
          kind: Cluster
        fieldPaths:
          - spec.externalClusters.0.name
