apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-assistant-postgres
spec:
  storage:
    size: 10Gi
  bootstrap:
    # initdb:
    #   database: home_assistant
    #   owner: home_assistant
    recovery:
      database: home_assistant
      owner: home_assistant
      source: home-assistant-postgres
