apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: velero
    namespace: velero
    releaseName: velero
    version: 7.2.2
    repo: https://vmware-tanzu.github.io/helm-charts
    valuesInline:
      backupsEnabled: false
      snapshotsEnabled: false
      deployNodeAgent: true
      configuration:
        features: EnableCSI
      initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.10.1
          volumeMounts:
            - mountPath: /target
              name: plugins
      credentials:
        secretContents:
          cloud: |
            [default]
            aws_access_key_id={{`{{ .VELERO_ACCESS_KEY_ID }}`}}
            aws_secret_access_key={{`{{ .VELERO_SECRET_ACCESS_KEY }}`}}
