apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/external-secrets-transformer
              subPath: external-secrets-transformer
              name: custom-tools
      initContainers:
        - name: external-secrets-transformer-installer
          image: alpine:3.20.3
          command:
            - sh
            - -c
            - |
              # Download external-secrets-transformer
              wget https://github.com/JonasKop/external-secrets-transformer/releases/download/0.4.1/external-secrets-transformer-linux-amd64
              install -m 0755 external-secrets-transformer-linux-amd64 /custom-tools/external-secrets-transformer

          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      volumes:
        - name: custom-tools
          emptyDir: {}
