apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "namespace.yaml"
helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    releaseName: ingress-nginx
    version: 4.11.3
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      controller:
        admissionWebhooks:
          enabled: false
  - name: ingress-nginx
    namespace: ingress-nginx
    releaseName: public-ingress-nginx
    version: 4.11.3
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      controller:
        ingressClass: public-nginx
        ingressClassResource:
          name: public-nginx
          controllerValue: k8s.io/public-ingress-nginx
        hostPort:
          enabled: true
        service:
          enabled: false
        tolerations:
          - key: "hetznerNoSchedule"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          - key: "hetznerNoExecute"
            operator: "Equal"
            value: "true"
            effect: "NoExecute"
        nodeSelector:
          node-type: hetzner
        admissionWebhooks:
          enabled: false
        updateStrategy:
          type: Recreate
          rollingUpdate: null
