apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: home-assistant-postgresql
  namespace: home-assistant
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    home_assistant: # database owner
      - superuser
      - createdb
  databases:
    home_assistant: home_assistant # dbname: owner
  postgresql:
    version: "15"
  clone:
    cluster: home-assistant-postgresql
    # uid:
    timestamp: "2024-05-20T15:50:00+00:00" 