apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snapshot-controller
resources:
  - namespace.yaml
  - volume-snapshot-class.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.1.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.1.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.1.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml

helmCharts:
  - name: snapshot-validation-webhook
    namespace: snapshot-controller
    releaseName: validation-webhook
    version: 1.9.0
    repo: https://piraeus.io/helm-charts/
  - name: snapshot-controller
    namespace: snapshot-controller
    releaseName: snapshot-controller
    version: 3.0.6
    repo: https://piraeus.io/helm-charts/
