global:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-app
          key: host
    - name: AUTHENTIK_POSTGRESQL__NAME
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-app
          key: dbname
    - name: AUTHENTIK_POSTGRESQL__PORT
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-app
          key: port
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-app
          key: user
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-app
          key: password

authentik:
  secret_key: "{{`{{ .AUTHENTIK_SECRET_KEY }}`}}"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: true
  postgresql:
    host: ""
    name: ""
    user: ""
    password: ""
    port: ""

server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    enabled: true
    # Specify kubernetes ingress controller class name
    ingressClassName: nginx
    hosts:
      - authentik.sjoedin.se
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.sjoedin.se

redis:
  enabled: true
