namespace: home-assistant
resources:
  - "../../base/home-assistant"

images:
  - name: homeassistant/home-assistant
    newTag: "2024.7.3"

secretGenerator:
  - name: home-assistant
    files:
      - secrets.yaml
      - serviceAccount.json
    options:
      disableNameSuffixHash: true

transformers:
  - "ESTransformer.yaml"
