apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: mosquitto
data:
  mosquitto.conf: |-
    allow_anonymous   false
    listener          1883
    password_file     /mosquitto/passwd