apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: mosquitto
data:
  mosquitto.conf: |-
    allow_anonymous   false
    listener          1883
    password_file     /mosquitto/passwd
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: mosquitto-0.0.1
  name: mosquitto
  namespace: mosquitto
stringData:
  MOSQUITTO_PASSWORD: '{{ .MOSQUITTO_PASSWORD }}'
  MOSQUITTO_USERNAME: '{{ .MOSQUITTO_USERNAME }}'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: mosquitto-0.0.1
  name: mosquitto
  namespace: mosquitto
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: mosquitto-0.0.1
  name: mosquitto-lb
  namespace: mosquitto
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: mosquitto-0.0.1
  name: mosquitto
  namespace: mosquitto
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: mosquitto
        image: ghcr.io/jonaskop/mosquitto:0.0.1
        name: mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 100Mi
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          name: config
          subPath: mosquitto.conf
      securityContext:
        runAsGroup: 1883
        runAsUser: 1883
      volumes:
      - configMap:
          name: mosquitto
        name: config
