apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - "namespace.yaml"
  - "postgres.yaml"
components:
  - ../../components/external-secrets-transformer
helmCharts:
  - name: authentik
    namespace: authentik
    valuesFile: values.yaml
    releaseName: authentik
    version: 2024.10.0
    repo: https://charts.goauthentik.io
