apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  storage:
    size: 5Gi
  bootstrap:
    # initdb:
    #   database: authentik
    #   owner: authentik
    recovery:
      database: authentik
      owner: authentik
      source: authentik-postgres
