apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: cluster-backups
  namespace: velero
spec:
  schedule: 0 4 * * *
  useOwnerReferencesInBackup: true
  template:
    excludedNamespaces:
      - kube-system
      - kube-public
      - kube-node-lease
      - velero
      - default
