apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor
parameters:
  csi.storage.k8s.io/fstype: xfs
  linstor.csi.linbit.com/autoPlace: "1"
  linstor.csi.linbit.com/storagePool: linstor_pool
provisioner: linstor.csi.linbit.com
volumeBindingMode: WaitForFirstConsumer
