apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - namespace.yaml
  - secret.yaml
helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    valuesInline:
      installCRDs: true
      dns01RecursiveNameservers: "1.1.1.1:53"
      dns01RecursiveNameserversOnly: true
    version: v1.16.1
    repo: https://charts.jetstack.io
patches:
  - patch: |-
      - op: replace
        path: "/spec/acme/email"
        value: 'jonas.k.sjodin@gmail.com'
    target:
      kind: ClusterIssuer
