apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-assistant-postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: home_assistant
      owner: home_assistant
