resources:
  - "namespace.yaml"
helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    valuesInline:
      controller:
        replicaCount: 2
    releaseName: ingress-nginx
    version: 4.10.1
    repo: https://kubernetes.github.io/ingress-nginx
