credentials:
  secretContents:
    cloud: |
      [default]  
      aws_access_key_id={{`{{ .GARAGE_VELERO_ACCESS_KEY_ID }}`}}
      aws_secret_access_key={{`{{ .GARAGE_VELERO_SECRET_ACCESS_KEY }}`}}
configuration:
  backupStorageLocation:
    - provider: aws
      bucket: velero
      config:
        region: garage
        s3ForcePathStyle: true # test without
        s3Url: http://garage:3900
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: garage
  features: EnableCSI

initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.7.0
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.1.0
    volumeMounts:
      - mountPath: /target
        name: plugins
